TAG: 'mile'
LOG_DIR: 'tensorboard_logs'

GPUS: 1
BATCHSIZE: 1
STEPS: 100000

OPTIMIZER:
  ACCUMULATE_GRAD_BATCHES: 32

RECEPTIVE_FIELD: 6
FUTURE_HORIZON: 6

PRETRAINED:
  PATH: ''

DATASET:
  DATAROOT: ''
